### ISSUE TITLE
Maybe create a new XsdUnresolved type of element

### ISSUE THREAD

**Issue by fmcarvalho** [lcduarte/XsdToJavaAPI#1]
It would be useful to have a distinct type of element, maybe `XsdUnresolvedelement` to identify those ones that have been not resolved yet. 

Since these elements will be replaced by a concrete element instance, I am not figuring out any problem in using a distinct type. I am not sure, but maybe you can check it better....

**Comment by lcduarte** [comment]
I've added a solution that consists in "wrapping" the XsdElementsBase objects.

The new solution consists of three types:

* ReferenceBase - An abstract type, with a getElement abstract method.
* UnsolvedReference - Extends ReferenceBase and represents a XsdElementBase object that has a value in its ref attribute.
* ConcreteElement - Extends ReferenceBase and represents a XsdElementBase object is resolved.

The main changes are:

* XsdElementBase::xsdParseSkeleton returns a ReferenceBase object instead of XsdElementBase;
* XsdParser::parse returns a List<ReferenceBase> and the caller can choose to filter the UnsolvedReferences or ConcreteElements objects with instanceof.
