### ISSUE TITLE
Misleading between setId() and attrId() on public API

### ISSUE THREAD

**Issue by fmcarvalho** [lcduarte/XsdToJavaAPI#31]
It is not clear for the end user programmer which one should be used: setId() or attrId().

I do not remember where `setId` came from? Can we suppress it or turn it non public?

**Comment by lcduarte** [comment]
The `setId(String id)` is the method added to replace the constructors with Element(String id)

The `attrId()` is automatic generated code due to the element having a attribute named id.

I agree that it is a bit confusing but I don't see name alternatives to `setId`.

A last resort option could be removing the `setId()` altogether, since it was only used in the `child(String id)` which was used to search for children in the current element and now there isn't many uses for that method, since the programmer can move around in the element "tree" with the parent method. 

But I don't like this idea very much since in some complex cases it could be useful to navigate to a certain element directly.

**Comment by fmcarvalho** [comment]
I think `setId` and `getId` does not solve all user needs. The lookup requirements can be close to using the DOM function [querySelector](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector) or jquery. If you want to navigate to a certain element directly then you must previously add to that element some identifier or class through `attrId()`  or `attrClass()`.

I think that xmlet and HtmlApi should only provide a method to look for an element in descendants recursively. Maybe `IElement` could provide a `IElement find(Predicate<IElement> p )`. Thus, we can perform any query checking the type of elements, attributes values, or whatever we want.

More user friendly APIs should be provided by upper layers like HtmlFlow. Maybe HtmlFlow should include an auxiliary static function (e.g. `$()`) which translates CSS style selector to a `Predicate<IElement>`. Then we could use this function like: `elem.find($("div.billboard"))`, which looks for a `div` with the class `billboard` in the children list of `elem`.

But for now the HtmlApi should only provide the underlie infrastructure, which is the  `IElement find(Predicate<IElement> p )`. 

Given that, I would purpose to remove the `setId()` and the `find()`.

**Comment by lcduarte** [comment]
I removed the `setId()`, `getId()` and `child(String id)`.

To replace the search functionality of the `child` method I added a `find` method with the following signature:

`<R extends IElement> Stream<R> find(Predicate<IElement> predicate)`

This way `HtmlFlow` can find one or multiple elements and obtain a Stream of a specific type in order to have access to that type specific functions. The function maintains the recursive functionality of `child` searching all the possible children of the current element for matches for the received predicate.
